# Generated by Django 5.2.4 on 2025-07-28 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HeroSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Creative', max_length=100)),
                ('typed_items', models.CharField(help_text='Comma-separated items for Typed.js', max_length=255)),
                ('description', models.TextField()),
                ('projects_completed', models.PositiveIntegerField(default=0)),
                ('years_experience', models.PositiveIntegerField(default=0)),
                ('happy_clients', models.PositiveIntegerField(default=0)),
                ('cta_primary_text', models.CharField(default='View My Work', max_length=50)),
                ('cta_primary_link', models.URLField(default='#portfolio')),
                ('cta_secondary_text', models.CharField(default='Get In Touch', max_length=50)),
                ('cta_secondary_link', models.URLField(default='#contact')),
                ('image', models.ImageField(blank=True, null=True, upload_to='hero/')),
                ('skill_1_icon', models.CharField(default='bi bi-palette', max_length=50)),
                ('skill_1_title', models.CharField(default='UI/UX Design', max_length=50)),
                ('skill_2_icon', models.CharField(default='bi bi-code-slash', max_length=50)),
                ('skill_2_title', models.CharField(default='Development', max_length=50)),
                ('skill_3_icon', models.CharField(default='bi bi-lightning', max_length=50)),
                ('skill_3_title', models.CharField(default='Creative Ideas', max_length=50)),
                ('twitter', models.URLField(blank=True, null=True)),
                ('linkedin', models.URLField(blank=True, null=True)),
                ('github', models.URLField(blank=True, null=True)),
                ('instagram', models.URLField(blank=True, null=True)),
            ],
        ),
    ]
